<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?></title>
    <style type="text/css">
        <?php echo file_get_contents($_SERVER['DOCUMENT_ROOT'] . '/css/swagger-ui.css'); ?>
    </style>
    <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />

</head>

<body>
<div id="swagger-ui"></div>
<script type="application/javascript">
    <?php echo file_get_contents($_SERVER['DOCUMENT_ROOT'] . '/js/swagger-ui-bundle.js'); ?>
</script>
<script type="application/javascript">
    <?php echo file_get_contents($_SERVER['DOCUMENT_ROOT'] . '/js/swagger-ui-standalone-preset.js'); ?>
</script>
<script>
    window.onload = function() {
        // Begin Swagger UI call region
        const ui = SwaggerUIBundle({
            url: "doc/yaml",
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        })
        // End Swagger UI call region

        window.ui = ui
    }
</script>

</body>
</html>